# Generated by Django 6.0.1 on 2026-02-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
