# Generated by Django 6.0.1 on 2026-02-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studenthobbies', models.CharField(choices=[('reading', 'reading'), ('travel', 'travel'), ('music', 'music')], max_length=100)),
                ('studentAddress', models.CharField(max_length=100)),
                ('studentphone', models.CharField(max_length=10)),
                ('studentgender', models.CharField(max_length=10)),
                ('studentdob', models.DateField()),
                ('studentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'db_table': 'studentprofile',
            },
        ),
    ]
