# Generated by Django 6.0.1 on 2026-02-10 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
